### ISSUE TITLE
Helm install failed

### ISSUE THREAD

**Issue by adengdai** [chaos-mesh/charts#2]
Command: helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --version v2.0.2
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]

The Command and the error message is shown as above,  And i Also install the minikube to start the chaos-mesh and also installed the kubectl as well.
I think it may be the Configuration Files Problem, Can somebody me a hand
Thank you So much

**Comment by cwen0** [comment]
@adengdai Sorry for my late reply! https://github.com/chaos-mesh/chaos-mesh/issues/2400 this issue maybe help you.

**Comment by cwen0** [comment]
This issue is duplicated with https://github.com/chaos-mesh/chaos-mesh/issues/2400, I will close it now.
